In [ ]:
#UDISE TABLE 2023-2024

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('UDISE_2023-24_Table_2.1.csv')

In [6]:
df.head()

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
0,1,India,1471891,248045828,9807600,50.0,29.4,9.8,10.8,48.7,25.4,14.9,10.9,24.0,28.6,16.2,31.1
1,2,Andaman and Nicobar Islands,412,72119,5750,50.7,19.2,13.1,17.0,46.1,23.6,15.9,14.4,17.3,16.9,17.5,48.3
2,3,Andhra Pradesh,61373,8741885,338293,61.5,13.5,18.9,6.1,46.1,25.7,16.5,11.6,28.6,14.0,42.7,14.7
3,4,Arunachal Pradesh,3490,323717,24700,48.6,36.8,9.5,5.2,53.7,24.0,13.4,8.9,19.1,42.6,20.6,17.6
4,5,Assam,56630,6922533,342199,66.2,16.7,12.5,4.7,53.4,25.1,14.3,7.2,32.6,20.5,29.1,17.8

In [7]:
df.tail(10)

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
27,28,Puducherry,735,244828,13202,37.1,9.4,25.2,28.3,46.2,23.5,16.0,14.3,14.0,5.9,22.9,57.3
28,29,Punjab,27404,5988681,273092,49.1,16.9,14.6,19.3,52.1,21.9,13.8,12.2,19.7,9.8,18.9,51.5
29,30,Rajasthan,107757,16786065,775745,35.0,32.0,6.8,26.1,49.6,24.7,14.5,11.2,10.8,28.8,9.2,51.2
30,31,Sikkim,1254,121395,15489,53.3,25.1,11.5,10.1,50.8,21.3,14.9,13.0,22.8,25.1,19.7,32.4
31,32,Tamil Nadu,58722,12993050,550558,57.9,17.1,9.7,15.3,45.7,24.6,15.9,13.8,20.6,13.2,12.5,53.8
32,33,Telangana,42901,7293644,341460,47.9,17.4,27.0,7.7,47.8,25.2,15.3,11.8,14.3,16.0,52.7,16.9
33,34,Tripura,4923,689408,37661,50.2,25.3,13.6,10.8,48.4,25.2,14.6,11.8,20.5,20.0,21.8,37.6
34,35,Uttar Pradesh,255087,41662794,1538479,52.3,34.0,4.7,9.0,49.4,25.4,13.7,11.5,36.6,34.1,5.6,23.7
35,36,Uttarakhand,22551,2372400,130741,57.3,24.4,6.2,12.0,47.7,24.2,15.0,13.1,23.7,25.2,8.8,42.3
36,37,West Bengal,93945,18015525,576557,79.3,9.2,3.5,8.1,47.0,24.5,17.0,11.5,52.2,6.7,6.5,34.6

In [8]:
df.shape

(37, 17)

In [9]:
df.columns

Index(['Sl. No.', 'India/State/UT', 'Total Number of - Schools',
       'Total Number of - Enrolments', 'Total Number of - Teachers',
       'Percentage Share of Schools by Category - Primary',
       'Percentage Share of Schools by Category - Upper Primary',
       'Percentage Share of Schools by Category - Secondary',
       'Percentage Share of Schools by Category - Higher Secondary',
       'Percentage Share of Enrolments by level -  Primary ',
       'Percentage Share of Enrolments by level -  Upper Primary ',
       'Percentage Share of Enrolments by level - Secondary',
       'Percentage Share of Enrolments by level - Higher Secondary',
       'Percentage Share of Teachers by School Category - Primary',
       'Percentage Share of Teachers by School Category - Upper Primary',
       'Percentage Share of Teachers by School Category - Secondary',
       'Percentage Share of Teachers by School Category - Higher Secondary'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 17 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Sl. No.                                                             37 non-null     int64
 1   India/State/UT                                                      37 non-null     str
 2   Total Number of - Schools                                           37 non-null     int64
 3   Total Number of - Enrolments                                        37 non-null     int64
 4   Total Number of - Teachers                                          37 non-null     int64
 5   Percentage Share of Schools by Category - Primary                   37 non-null     float64
 6   Percentage Share of Schools by Category - Upper Primary             37 non-null     float64
 7   Percentage Share of Schools by Category - Secondary                 37 non-null     float64
 8   Percentage Share of Schools by Category - Higher Secondary          37 non-null     float64
 9   Percentage Share of Enrolments by level -  Primary                  37 non-null     float64
 10  Percentage Share of Enrolments by level -  Upper Primary            37 non-null     float64
 11  Percentage Share of Enrolments by level - Secondary                 37 non-null     float64
 12  Percentage Share of Enrolments by level - Higher Secondary          37 non-null     float64
 13  Percentage Share of Teachers by School Category - Primary           37 non-null     float64
 14  Percentage Share of Teachers by School Category - Upper Primary     37 non-null     float64
 15  Percentage Share of Teachers by School Category - Secondary         37 non-null     float64
 16  Percentage Share of Teachers by School Category - Higher Secondary  37 non-null     float64
dtypes: float64(12), int64(4), str(1)
memory usage: 5.0 KB

In [11]:
df.sort_values(by=['Percentage Share of Schools by Category - Secondary', 'Percentage Share of Teachers by School Category - Upper Primary'], ascending=False).head(5)

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
6,7,Chandigarh,230,265706,10237,6.1,18.3,30.4,45.2,45.0,23.9,15.3,15.8,2.0,7.5,26.2,64.4
10,11,Goa,1487,304735,14594,58.0,5.2,28.4,8.4,48.5,23.7,15.1,12.8,20.4,4.4,53.2,22.0
32,33,Telangana,42901,7293644,341460,47.9,17.4,27.0,7.7,47.8,25.2,15.3,11.8,14.3,16.0,52.7,16.9
27,28,Puducherry,735,244828,13202,37.1,9.4,25.2,28.3,46.2,23.5,16.0,14.3,14.0,5.9,22.9,57.3
16,17,Karnataka,75869,11926303,433942,30.9,40.0,21.5,7.6,46.0,26.5,17.3,10.2,10.9,34.2,38.7,16.2

In [12]:
df.describe()

,Sl. No.,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
count,37.000000,3.700000e+01,3.700000e+01,3.700000e+01,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,19.000000,7.956168e+04,1.340788e+07,5.301405e+05,47.435135,26.529730,12.770270,13.259459,49.981081,24.275676,14.700000,11.035135,21.289189,25.681081,20.027027,32.986486
std,10.824355,2.407658e+05,4.057760e+07,1.598759e+06,12.635844,10.954955,7.426935,9.885299,4.459125,1.943994,1.481178,2.427415,9.214053,13.770517,12.912067,16.900151
min,1.000000,3.700000e+01,1.259100e+04,9.110000e+02,6.100000,5.200000,0.000000,2.900000,44.200000,20.500000,10.400000,5.100000,2.000000,4.400000,0.000000,9.400000
25%,10.000000,3.490000e+03,3.237170e+05,2.470000e+04,40.500000,17.400000,7.300000,6.200000,46.200000,23.400000,13.700000,9.100000,16.200000,14.000000,10.700000,18.200000
50%,19.000000,2.351700e+04,5.599742e+06,2.065910e+05,48.600000,25.300000,11.500000,10.100000,48.700000,24.600000,14.900000,11.500000,20.500000,25.200000,18.900000,29.400000
75%,28.000000,6.137300e+04,1.149671e+07,3.940530e+05,53.300000,35.700000,16.500000,16.000000,52.100000,25.700000,15.900000,13.000000,23.900000,36.500000,26.200000,48.700000
max,37.000000,1.471891e+06,2.480458e+08,9.807600e+06,79.300000,50.400000,30.400000,45.200000,63.900000,27.600000,17.300000,15.800000,52.200000,56.100000,53.200000,71.500000

In [13]:
df["Percentage Share of Enrolments by level -  Upper Primary "]

0     25.4
1     23.6
2     25.7
3     24.0
4     25.1
5     26.4
6     23.9
7     25.3
8     25.1
9     25.9
10    23.7
11    27.6
12    26.6
13    23.4
14    21.5
15    26.5
16    26.5
17    23.7
18    20.5
19    22.1
20    25.9
21    25.9
22    21.7
23    20.6
24    22.2
25    21.3
26    27.6
27    23.5
28    21.9
29    24.7
30    21.3
31    24.6
32    25.2
33    25.2
34    25.4
35    24.2
36    24.5
Name: Percentage Share of Enrolments by level -  Upper Primary , dtype: float64

In [14]:
df["Percentage Share of Enrolments by level - Higher Secondary"]

0     10.9
1     14.4
2     11.6
3      8.9
4      7.2
5      7.7
6     15.8
7      9.7
8      8.4
9     13.5
10    12.8
11     8.9
12    11.8
13    13.1
14     9.2
15     9.1
16    10.2
17    14.2
18     7.5
19    13.1
20     9.0
21    13.0
22     9.8
23     5.1
24     8.3
25     9.2
26    11.7
27    14.3
28    12.2
29    11.2
30    13.0
31    13.8
32    11.8
33    11.8
34    11.5
35    13.1
36    11.5
Name: Percentage Share of Enrolments by level - Higher Secondary, dtype: float64

In [15]:
df.sort_values(
    by="Percentage Share of Schools by Category - Primary",
    ascending=False
)[["India/State/UT", "Percentage Share of Schools by Category - Primary"]].head(10)

      India/State/UT  Percentage Share of Schools by Category - Primary
36       West Bengal                                               79.3
4              Assam                                               66.2
23         Meghalaya                                               62.7
2     Andhra Pradesh                                               61.5
13  Himachal Pradesh                                               60.8
10               Goa                                               58.0
31        Tamil Nadu                                               57.9
7       Chhattisgarh                                               57.3
35       Uttarakhand                                               57.3
30            Sikkim                                               53.3

In [18]:
df[df["Percentage Share of Schools by Category - Primary"] > 50][[
    "India/State/UT",
    "Percentage Share of Schools by Category - Primary"
]]

,India/State/UT,Percentage Share of Schools by Category - Primary
1,Andaman and Nicobar Islands,50.7
2,Andhra Pradesh,61.5
4,Assam,66.2
7,Chhattisgarh,57.3
10,Goa,58.0
13,Himachal Pradesh,60.8
15,Jharkhand,52.5
22,Manipur,52.7
23,Meghalaya,62.7
30,Sikkim,53.3
31,Tamil Nadu,57.9
33,Tripura,50.2
34,Uttar Pradesh,52.3
35,Uttarakhand,57.3
36,West Bengal,79.3

In [19]:
df["Percentage Share of Schools by Category - Upper Primary"].mean()

np.float64(26.529729729729727)

In [20]:
df["Percentage Share of Schools by Category - Upper Primary"].mean().round(2)

np.float64(26.53)

In [21]:
df["Percentage Share of Schools by Category - Upper Primary"].median()

np.float64(25.3)

In [22]:
df["Percentage Share of Schools by Category - Secondary"].min()

np.float64(0.0)

In [23]:
df["Percentage Share of Schools by Category - Secondary"].max()

np.float64(30.4)

In [25]:
df.isna().sum().sort_values(ascending=False)

Sl. No.                                                               0
India/State/UT                                                        0
Total Number of - Schools                                             0
Total Number of - Enrolments                                          0
Total Number of - Teachers                                            0
Percentage Share of Schools by Category - Primary                     0
Percentage Share of Schools by Category - Upper Primary               0
Percentage Share of Schools by Category - Secondary                   0
Percentage Share of Schools by Category - Higher Secondary            0
Percentage Share of Enrolments by level -  Primary                    0
Percentage Share of Enrolments by level -  Upper Primary              0
Percentage Share of Enrolments by level - Secondary                   0
Percentage Share of Enrolments by level - Higher Secondary            0
Percentage Share of Teachers by School Category - Primary             0
Percentage Share of Teachers by School Category - Upper Primary       0
Percentage Share of Teachers by School Category - Secondary           0
Percentage Share of Teachers by School Category - Higher Secondary    0
dtype: int64

In [26]:
df[[
    "India/State/UT",
    "Total Number of - Schools",
    "Percentage Share of Schools by Category - Primary"
]].sort_values(
    "Total Number of - Schools",
    ascending=False
).head(10)

,India/State/UT,Total Number of - Schools,Percentage Share of Schools by Category - Primary
0,India,1471891,50.0
34,Uttar Pradesh,255087,52.3
20,Madhya Pradesh,123412,49.4
21,Maharashtra,108237,46.1
29,Rajasthan,107757,35.0
5,Bihar,94686,44.0
36,West Bengal,93945,79.3
16,Karnataka,75869,30.9
26,Odisha,61693,46.4
2,Andhra Pradesh,61373,61.5